const orderActionTypes = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAILED: "ORDER_CREATE_FAILED",
  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAILED: "ORDER_DETAILS_FAILED"
};

export default orderActionTypes;
