const orderActionTypes = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAILED: "ORDER_CREATE_FAILED",

  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAILED: "ORDER_DETAILS_FAILED",

  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAILED: "ORDER_PAY_FAILED",
  ORDER_PAY_RESET: "ORDER_PAY_RESET",

  ORDER_DELIVERED_REQUEST: "ORDER_DELIVERED_REQUEST",
  ORDER_DELIVERED_SUCCESS: "ORDER_DELIVERED_SUCCESS",
  ORDER_DELIVERED_FAILED: "ORDER_DELIVERED_FAILED",
  ORDER_DELIVERED_RESET: "ORDER_DELIVERED_RESET",

  ORDER_LIST_REQUEST: "ORDER_LIST_REQUEST",
  ORDER_LIST_SUCCESS: "ORDER_LIST_SUCCESS",
  ORDER_LIST_FAILED: "ORDER_LIST_FAILED",
  ORDER_LIST_RESET: "ORDER_LIST_RESET"
};

export default orderActionTypes;
