const orderActionTypes = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAILED: "ORDER_CREATE_FAILED"
};

export default orderActionTypes;
